### ISSUE TITLE
panaroo to pagoo, support for bakta annos

### ISSUE THREAD

**Issue by herber4** [iferres/pagoo#57]
Hi pagoo, 

love the program. was working great when using prokka annotations, however, I just tried to redo an analysis with bakta annotations and when creating the running the panaroo_2_pagoo and roary_2_pagoo was supplied with this error -

two issues I got were 1: 

Reading gff file /Users/XXXX/Desktop/XXXX/XXXXXX/bakta_pano/bakta_gff//XXXXX.gff3
Error in .Call2("C_solve_user_SEW", refwidths, start, end, width, translate.negative.coord,  : 
  solving row 61: 'allow.nonnarrowing' is FALSE and the supplied end (47314) is > refwidth

it seems to be an issue with reading in the coordinates of an annotation in the gff, I am unsure if this is due to BAKTA calling genes whose coordinates span the start and residues on the plasmid. I took out that line in the gff and it worked fine. 

then I ran into this error: 
Reading csv file (roary).
Processing csv file.
Reading gff file /Users/herber4/Desktop/COPPER/COPPER_MASTER/bakta_pano/bakta_gff/R1_polished.gff3
Reading gff file /Users/herber4/Desktop/COPPER/COPPER_MASTER/bakta_pano/bakta_gff/T1_polished.gff3
Reading gff file /Users/herber4/Desktop/COPPER/COPPER_MASTER/bakta_pano/bakta_gff/X_albilineans_FJ.1.gff3
Reading gff file /Users/herber4/Desktop/COPPER/COPPER_MASTER/bakta_pano/bakta_gff/X_arboricola_juglandis_CPBF1494.gff3
Reading gff file /Users/herber4/Desktop/COPPER/COPPER_MASTER/bakta_pano/bakta_gff/X_axonopodis_vasculorum_NCPPB796.gff3
Reading gff file /Users/herber4/Desktop/COPPER/COPPER_MASTER/bakta_pano/bakta_gff/X_campestris_musacearum_NCPPB4379.gff3
Reading gff file /Users/herber4/Desktop/COPPER/COPPER_MASTER/bakta_pano/bakta_gff/X_campestris_raphani_MAF106181.gff3
Reading gff file /Users/herber4/Desktop/COPPER/COPPER_MASTER/bakta_pano/bakta_gff/X_citri_citri_MN12.gff3
Reading gff file /Users/herber4/Desktop/COPPER/COPPER_MASTER/bakta_pano/bakta_gff/X_cucurbitae_ATCC23378.gff3
Reading gff file /Users/herber4/Desktop/COPPER/COPPER_MASTER/bakta_pano/bakta_gff/X_euroxanthea.gff3
Reading gff file /Users/herber4/Desktop/COPPER/COPPER_MASTER/bakta_pano/bakta_gff/X_euvesicatoria_alfalfae_CFBP3836.gff3
Reading gff file /Users/herber4/Desktop/COPPER/COPPER_MASTER/bakta_pano/bakta_gff/X_fragariae_PD885.gff3
Reading gff file /Users/herber4/Desktop/COPPER/COPPER_MASTER/bakta_pano/bakta_gff/X_hortorum_B07007.gff3
Reading gff file /Users/herber4/Desktop/COPPER/COPPER_MASTER/bakta_pano/bakta_gff/X_hyacinthi_CFBP1156.gff3
Reading gff file /Users/herber4/Desktop/COPPER/COPPER_MASTER/bakta_pano/bakta_gff/X_hydrangeae_GBBC2199.gff3
Reading gff file /Users/herber4/Desktop/COPPER/COPPER_MASTER/bakta_pano/bakta_gff/X_oryzae_oryzicola_YM15.gff3
Reading gff file /Users/herber4/Desktop/COPPER/COPPER_MASTER/bakta_pano/bakta_gff/X_theicola_CFBP4691.gff3
Reading gff file /Users/herber4/Desktop/COPPER/COPPER_MASTER/bakta_pano/bakta_gff/X_translucens_undulosa_XtLr8.gff3
Reading gff file /Users/herber4/Desktop/COPPER/COPPER_MASTER/bakta_pano/bakta_gff/X_vesicatoria_ATCC35937_LMG911.gff3
Reading gff file /Users/herber4/Desktop/COPPER/COPPER_MASTER/bakta_pano/bakta_gff/Xap_15-088.gff3
Reading gff file /Users/herber4/Desktop/COPPER/COPPER_MASTER/bakta_pano/bakta_gff/Xap_CITA33.gff3
Reading gff file /Users/herber4/Desktop/COPPER/COPPER_MASTER/bakta_pano/bakta_gff/Xap_CuR.gff3
Reading gff file /Users/herber4/Desktop/COPPER/COPPER_MASTER/bakta_pano/bakta_gff/Xap_IVIA2626.1.gff3
Reading gff file /Users/herber4/Desktop/COPPER/COPPER_MASTER/bakta_pano/bakta_gff/Xap_Xcp1.gff3
Reading gff file /Users/herber4/Desktop/COPPER/COPPER_MASTER/bakta_pano/bakta_gff/Xcc_03-1638-1-1.gff3
Reading gff file /Users/herber4/Desktop/COPPER/COPPER_MASTER/bakta_pano/bakta_gff/Xcc_GD82.gff3
Reading gff file /Users/herber4/Desktop/COPPER/COPPER_MASTER/bakta_pano/bakta_gff/Xhc_ICMP7383.gff3
Reading gff file /Users/herber4/Desktop/COPPER/COPPER_MASTER/bakta_pano/bakta_gff/Xhv_CFBP498.gff3
Reading gff file /Users/herber4/Desktop/COPPER/COPPER_MASTER/bakta_pano/bakta_gff/Xp_LH3.gff3
Error in `[[<-`(`*tmp*`, name, value = "X_albilineans_FJ.1.gff3") : 
  1 elements in value to replace 0 elements

is there anything you can do to help trouble shoot this? 

best, 

Austin

**Comment by iferres** [comment]
Hi @herber4 , what's the pagoo version you are using?

**Comment by herber4** [comment]
currently using v0.3.13

Rstudio dev version
Version 2022.11.0-daily+139 (2022.11.0-daily+139)

**Comment by iferres** [comment]
Thanks, you are using the latest.

Regarding the first error, did it pop up only in a single file or fails with all the gff3?

And 2nd, could you provide me the "X_albilineans_FJ.1.gff3" file so I can have a look? Same for the first file if it a single line.

**Comment by herber4** [comment]
[X_albilineans_FJ1.txt](https://github.com/iferres/pagoo/files/9497882/X_albilineans_FJ1.txt)

yeah, the 1st error only popped up with that GFF sample. simply removing the entry makes it compatible, however, losing data is never desirable. 

I have provided the GFF3 as a txt. It may be helpful to annotate some of your own w BAKTA, run it through panaroo or Roary and try to get them into pagoo. as there were several other errors appearing as well. 

I just moved forward without putting the GFFs in and will query cluster alignments in a different method for now. 

thanks!

**Comment by iferres** [comment]
Thank you @herber4, I will have a look at it as soon as I can.

**Comment by iferres** [comment]
Hey @herber4 , my desktop computer decided to take vacations a few days (:tired_face:), and my personal laptop isn't powerful enough to run heavy software like bakta. Still, I noticed that there were some differences between the gff from prokka and the from bakta you sent me. I just pushed a fix to address that. Not sure if it will solve all your issues but hopefully some. If you want to give it a try, reinstall pagoo from github:
```r
if (!require("devtools")) install.packages("devtools")
devtools::install_github('iferres/pagoo')
```
Let me know.

I will let this issue open until I can correctly address this. 
Thank you for reporting!

**Comment by herber4** [comment]
thanks, I will have to give it a try, this is a side project so I really only work on it a bit each week. and though I don't rely on importing the gff files for sequencing analysis, I am able to fetch and query the cluster alignments with other CLI tools, however, others may not be able to do so. 

Can I request an enhancement while I'm here? May I suggest implementing the "pheatmap" package in some way. it is helpful for hierarchical biclustering and may really enhance the "$gg_binmap" type of plots. 

Best, 

Austin

**Comment by iferres** [comment]
Totally agree. In fact, I'm also interested in sorting this out since in the latest versions of Bakta identifies pseudogenes and I'm working with a species where this seems to be a strong evolutionary force.  

Regarding the pheatmap, yes, I would also like to improve that function. Actually, this was already discussed in this issue: https://github.com/iferres/pagoo/issues/45#issuecomment-899833446. It's on my side. More time to put on this is something I would like to have 😅. But see that thread, I wrote some code to attach a tree to a heatmap, respecting the tips ordering in the latter. I may help you.

**Comment by gpmoran** [comment]
Hi @iferres and @herber4 

I am also using panaroo outputs with panaroo_2_pagoo and I run into the same error message:

Error in `[[<-`(`*tmp*`, name, value = "40A2") : 
  1 elements in value to replace 0 elements

"40A2" is the first strain in the gene_presence_absence.csv. If I remove this column and the associated .gff file from the analysis the error moves on to the strain in the next column.....
Same error if I use roary_2_pagoo. 
I am running version 0.3.13 and use Prokka for annotation.

thanks
Gary

**Comment by iferres** [comment]
Thanks Gary, before trying anything else, could you re install pagoo from source and try again? I pushed some code to address this issue, but I haven't sent it to CRAN yet:
```r
if (!require("devtools")) install.packages("devtools")
devtools::install_github('iferres/pagoo')
```
You should have version 0.3.14 installed after that. Try it in a fresh R session to avoid installing but not loading the latest version. 
Please, let my know if that solves that issue.

**Comment by gpmoran** [comment]
Thank you for the quick response. I have installed version 0.3.14 and started a new session but I still get the same error:

Error in `[[<-`(`*tmp*`, name, value = "40A2") : 
  1 elements in value to replace 0 elements

**Comment by iferres** [comment]
Ok, could you provide a reproducible example (i.e. data to recreate the error), so I can debug pagoo? The less data, the better.

**Comment by gpmoran** [comment]
Many thanks for your time!
I have tested this with a truncated data set that gives the same error. The data can be found here:
https://www.dropbox.com/sh/jh4a2xd740rpvuu/AAAE2nqcvZJVgFUMg68U25lta?dl=0

I simply run the following:
gffs <-list.files(path="~/Test_data", pattern = "[.]gff$", full.names = TRUE)
fn_csv <- "~/Test_data/gene_presence_absence.csv"
p <- panaroo_2_pagoo(gene_presence_absence_csv = fn_csv, gffs = gffs)

Thanks

**Comment by iferres** [comment]
I have just pushed changes which address this issue. Re install pagoo (from source) and don't hesitate to reopen it if still fails.

**Comment by gpmoran** [comment]
Thanks @iferres. The good news is the test data set we shared is working fine. My full data set however gives an error about row.names:

Error in (function (..., row.names = NULL, check.rows = FALSE, check.names = TRUE,  : 
  row names contain missing values

Perhaps this a problem with my gene_presence_absence.csv file? I am searching for missing row values but I cannot see any?

**Comment by herber4** [comment]
try loading your gene_pres_abs.csv without the associated gffs and see if pagoo takes it. 

pano <- ("/path/2/gene_pres_abs/gene_presence_absence.csv")
pag <- panaroo_2_pagoo(pano)
if it pagoo reads it, then the issue is not with your gene_presence_absencefile and instead with your GFFs, gff directory, or naming conventions between ur gffs and what's in the gene PA table. 

as panaroo outputs individual alignments for core and pan genes. it is possible to query these quite easily without pagoo, though pagoo provides a great interface for doing so. 

best, 

Austin Herbert
Clemson University
Center for Human Genetics

**Comment by gpmoran** [comment]
I am making progress thanks to everyones help. Through trial and error I have found that the first 25 of my .gff files load perfectly. Number 26 breaks pagoo! I cannot see any difference between this sample and the others. They are all generated in Prokka. Just leaving this one out of the full set does not fix things, so there may be a few other samples with the same issue.

**Comment by iferres** [comment]
Thank you both for your reports and comments, this helps a lot to improve pagoo. 
@gpmoran could you attach the problematic gff?
A way to test if it is the gff file or the parser which is reading it is to call the internal function directly over the problematic file:
```r
pagoo:::read_gff(gff_file)
```

**Comment by gpmoran** [comment]
Hi @iferres 
The read_gff function loads this .gff file into pagoo. The file is 165B.gff and I have added it to the link here with the gene presence absence file. Essentially, I can load the first 25 .gffs in the file, but when I add 165B.gff, pagoo gives the error.
https://www.dropbox.com/sh/jh4a2xd740rpvuu/AAAE2nqcvZJVgFUMg68U25lta?dl=0

**Comment by gpmoran** [comment]
Sorry, I didn't share all of the gff files. I have done so now, there should be 76 gff files and 76 columns, my apologies!
https://www.dropbox.com/sh/4ds12kyjyr6439g/AAB9dCKDq8sqTNDQw-4g-cSOa?dl=0
I appreciate you time in taking a closer look at this,
Gary

**Comment by iferres** [comment]
Ok, now I think is fixed. Was a pattern matching bug (regex). Re-install from source. Let me know. Bests!

**Comment by gpmoran** [comment]
Wonderful, that fixed it! Looking forward to having fun with Pagoo. Many thanks for your kind assistance,

Gary

**Comment by gpmoran** [comment]
Hi @iferres , we are using Panaroo 1.2.9
I had manually deleted the column "Non-unique Gene name" in my gene presence absence as it looks like pagoo did not use it?

Gary

**Comment by iferres** [comment]
Ahhhhh, ok. That was the issue. I was parsing the csv by index, not by column names 🤦🏻 . Ok I will push a patch ASAP. Thanks!

**Comment by herber4** [comment]
I have been using panaroo v1.2.10
